all: ex1.out ex2.out ex3.out

ex1.out:	example1.cpp
	g++ -g -Wall example1.cpp -o ex1.out
	ex1.out


ex2.out:	example2.cpp
	g++ -g -Wall example2.cpp -o ex2.out
	ex2.out

	
ex3.out:	example3.cpp
	g++ -g -Wall example3.cpp -o ex3.out
	ex3.out



